### ISSUE TITLE
Display dataset size in dataset retriever cli step

### ISSUE THREAD

**Issue by neubig** [neulab/prompt2model#253]
Currently in the CLI, the dataset retriever retrieves datasets, but it's not clear how big they are. I'd like to avoid downloading a huge dataset with multiple millions of examples, so it'd be nice to tell the user what size the datasets are.

**Comment by zhaochenyang20** [comment]
@viswavi I think that the dataset retriever only retrieves datasets, which are not that huge.

**Comment by hitenvidhani** [comment]
Hi @neubig , can I take this up?

**Comment by viswavi** [comment]
@hitenvidhani absolutely! Please message me on discord if you have any questions
