### ISSUE TITLE
Add an example to explanation of how to write a good prompt

### ISSUE THREAD

**Issue by neubig** [neulab/prompt2model#261]
There are some [instructions about how to write a good prompt](https://github.com/neulab/prompt2model/#how-to-write-a-good-prompt).

These are nice instructions, but I am much better at learning by example. It'd be good if we could add an example as well.

**Comment by zhaochenyang20** [comment]
Will do!

**Comment by zhaochenyang20** [comment]
Should I provide the three initial prompts of our experiments?

**Comment by neubig** [comment]
Done
