### ISSUE TITLE
Dependencies are too strict

### ISSUE THREAD

**Issue by neubig** [neulab/prompt2model#296]
Currently all of our Python dependencies are [set to "==" dependencies](https://github.com/neulab/prompt2model/blob/159b57fcd9220229df9f3ee47820dc7ab7e818cb/pyproject.toml#L24-L46), but this will make it difficult for the library to be cross-compatible with any other software that may live in the ecosystem. We should relax these requirements.

**Comment by zhaochenyang20** [comment]
Yeah. I think only a few of them regarding huggingface and numpy are strict. Others can be relaxed.
