### ISSUE TITLE
dependence  conflict of protobuf

### ISSUE THREAD

**Issue by Jessy-Huang** [neulab/prompt2model#309]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-api-core 2.11.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5, but you have protobuf 3.20.0 which is incompatible.
google-cloud-bigquery 3.10.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.0 which is incompatible.
google-cloud-bigquery-connection 1.12.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.0 which is incompatible.
google-cloud-bigquery-storage 2.22.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.0 which is incompatible.
google-cloud-datastore 2.15.2 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.0 which is incompatible.
google-cloud-firestore 2.11.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.0 which is incompatible.
google-cloud-functions 1.13.2 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.0 which is incompatible.
google-cloud-language 2.9.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.0 which is incompatible.
google-cloud-translate 3.11.3 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.0 which is incompatible.
googleapis-common-protos 1.60.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5, but you have protobuf 3.20.0 which is incompatible.
grpc-google-iam-v1 0.12.6 requires protobuf!=3.20.0,!=3.20.1,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.0 which is incompatible.
tensorflow 2.12.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3, but you have protobuf 3.20.0 which is incompatible.
tensorflow-metadata 1.14.0 requires protobuf<4.21,>=3.20.3, but you have protobuf 3.20.0 which is incompatible.
Successfully installed Mako-1.2.4 accelerate-0.22.0 aiofiles-23.2.1 aiolimiter-1.1.0 alembic-1.11.3 autofaiss-2.15.8 bert-score-0.3.13 cbor-1.0.0 cbor2-5.4.6 cmaes-0.10.0 colorama-0.4.6 colorlog-6.7.0 cramjam-2.7.0 datasets-2.14.4 dill-0.3.7 embedding-reader-1.5.1 evaluate-0.4.0 faiss-cpu-1.7.4 fastapi-0.103.0 fastparquet-2023.7.0 ffmpy-0.3.1 fire-0.4.0 gradio-3.41.2 gradio-client-0.5.0 h11-0.14.0 httpcore-0.17.3 httpx-0.24.1 huggingface-hub-0.16.4 ijson-3.2.3 indxr-0.1.4 inscriptis-2.3.2 ir-datasets-0.5.5 krovetzstemmer-0.8 latex2mathml-3.76.0 lz4-4.3.2 mdtex2html-1.2.0 multipipe-0.1.0 multiprocess-0.70.15 oneliner-utils-0.1.2 openai-0.27.10 optuna-3.3.0 orjson-3.9.5 portalocker-2.7.0 prompt2model-0.0.4 protobuf-3.20.0 pyautocorpus-0.1.12 pydub-0.25.1 pyfiglet-0.8.post1 pystemmer-2.0.1 python-multipart-0.0.6 ranx-0.3.16 responses-0.18.0 retriv-0.2.3 sacrebleu-2.3.1 safetensors-0.3.3 semantic-version-2.10.0 sentencepiece-0.1.99 starlette-0.27.0 tevatron-0.1.0 tiktoken-0.4.0 tokenizers-0.13.3 transformers-4.32.1 trec-car-tools-2.6 unidecode-1.3.6 unlzw3-0.2.2 uvicorn-0.23.2 warc3-wet-0.2.3 warc3-wet-clueweb09-0.2.5 websockets-11.0.3 xxhash-3.3.0 zlib-state-0.1.5
WARNING: The following packages were previously imported in this runtime:
  [google]
You must restart the runtime in order to use newly installed versions.

**Comment by neubig** [comment]
Thanks for reporting this! A few comments:

1. Most importantly: this should not be a blocking error. Please try to just continue using prompt2model and it should work.
2. This pinned dependency was introduced due to an issue with Hugging Face models that required protobuf version 3.20.0. It might be fixed though, so we can experiment with unpinning the version: https://github.com/huggingface/transformers/pull/24599

**Comment by neubig** [comment]
Fixed by #372
