### ISSUE TITLE
Tuning of model and dataset retrievers

### ISSUE THREAD

**Issue by neubig** [neulab/prompt2model#314]
Currently our model and dataset retrievers are not perfect, and it would be good to have a way to make them better.

One way we can do so is by explicitly training the model/dataset retrievers to:

1. Retrieve multiple datasets (models) and run the prompt2model pipeline with all of them
2. Take the resulting accuracy scores, and train the retriever so that the retriever gives higher scores to datasets (models) that give higher accuracy scores for the full pipeline

This would result in a training objective that explicitly rewards retrieving of datasets (models) that give high accuracy.

This would also be helpful for #285 , as it would reduce the need for human intervention when selecting models.

**Comment by zhaochenyang20** [comment]
Also, here is something related:

https://github.com/stanfordnlp/dspy

Vijay and I actually thought about using LLM to automatically select columns and datasets, but just by prompting a row LLM, it is somehow impractical. Now, with DSPy, it seems that we can achieve this.
