### ISSUE TITLE
Better description/organization of developer install

### ISSUE THREAD

**Issue by neubig** [neulab/prompt2model#319]
Currently, there are a few issues with the directions about how developers can install prompt2model:

1. We have no description in `contributing.md` about how we can install the toolkit locally
2. `pyprojects.toml` doesn't have requirements for developer tools such as pre-commit and pytest. We can add these with `pyproject.optional-dependencies`: https://setuptools.pypa.io/en/latest/userguide/dependency_management.html

Once done, we should be able to run `pip install ".[dev]"` to install the requirements and the development dependencies, and add these directions to `contributing.md`

**Comment by hitenvidhani** [comment]
I'll take this one up too @neubig @viswavi
