### ISSUE TITLE
Update the readme and class name of `OpenAIDatasetGenerator`

### ISSUE THREAD

**Issue by zhaochenyang20** [neulab/prompt2model#332]
We integrated `litellm` into `Prompt2Model` to support more API-based models. But there are two things remain:

1. The class name `OpenAIDatasetGenerator` is confusing since we already support models far beyond OpenAI models.
2. The readme of `DatasetGenerator` is unchanged.
3. There are many type hints like `openai.Completion`, which should be changed correspondingly.

**Comment by neubig** [comment]
Fixed in https://github.com/neulab/prompt2model/pull/331
