### ISSUE TITLE
DatasetGenerator doesn't stop generating?

### ISSUE THREAD

**Issue by neubig** [neulab/prompt2model#333]
In this code block, I had an instance of the dataset generator not stopping and continuing generating. I'm investigating this, it may be a bug introduced by the switch in #324 

```python
from prompt2model.dataset_generator import PromptBasedDatasetGenerator, DatasetSplit

dataset_generator = PromptBasedDatasetGenerator(
    initial_temperature=0.3,
    max_temperature=1.4,
    responses_per_request=3,
    max_api_calls=10000,
    requests_per_minute=80,
)
generated_dataset = dataset_generator.generate_dataset_split(
    prompt_spec, 5000, split=DatasetSplit.TRAIN
)
generated_dataset.save_to_disk("generated_dataset")
```

**Comment by zhaochenyang20** [comment]
Hmmm. I've written a lot of unit tests to test `DatasetGenerator` ends correctly. It seems that these mocks in the unit tests of `DatasetGenerator` is invalid now. 🤔
