### ISSUE TITLE
Error when running example

### ISSUE THREAD

**Issue by albertah1** [neulab/prompt2model#348]
I am running prompt2model_demo.py and enter the example text. This error appears repeatedly immediately:

Parsing prompt...
ERROR:root:{'max_tokens': 4000, 'input_cost_per_token': 1.5e-06, 'output_cost_per_token': 2e-06} is not of type 'integer' - 'max_tokens'
ERROR:root:{'max_tokens': 4000, 'input_cost_per_token': 1.5e-06, 'output_cost_per_token': 2e-06} is not of type 'integer' - 'max_tokens'

**Comment by chintanshrinath** [comment]
@albertah1 
I am getting same issue

**Comment by viswavi** [comment]
The latest release ([v0.0.6 on PyPi](https://pypi.org/project/prompt2model/0.0.6/)) should fix these issues @albertah1 @chintanshrinath. Apologies for the reliability issues here.
