### ISSUE TITLE
ERROR:root:This model's maximum context length is 4097 tokens

### ISSUE THREAD

**Issue by lishiyu** [neulab/prompt2model#353]
In the execution instance, the cue words display as oversized.
![image](https://github.com/neulab/prompt2model/assets/36871640/82e9e4c7-e1c4-40b7-810a-8bf908ec8235)

**Comment by neubig** [comment]
Thanks for the error report @lishiyu !

Would you mind telling us which prompt you're using, or any other information that would help debug? (You could also send it to us via email or private discord message if you don't want to share publicly.)

**Comment by lishiyu** [comment]
Are you asking which model you are using? I am using GPT-3.5-turbo-16k

**Comment by viswavi** [comment]
Hmm the 16k should not give an error for a 4k token limit. Can you share (or privately message) the prompt so we can reproduce and test your error?

**Comment by lishiyu** [comment]
Sorry, I replied wrongly, but even if I use 16K, it will display more than 16,385 tokens. I am using the demo in prompt_examples.mdSorry，

**Comment by saum7800** [comment]
Which example in `prompt_examples.md`? QA/Temporal Expression Normalization/Japanese to Python?

**Comment by lishiyu** [comment]
first demo，”Your task is to generate an answer to a natural question. In this task, the input is a string that consists of both a question and a context passage. The context is a descriptive passage related to the question and contains the answer. And the question can range from Math, Cultural, Social, Geometry, Biology, History, Sports, Technology, Science, and so on“，but i modify ‘APIAgent’ method，set 'max_tokens' this ok, i dont know is the method question.

**Comment by viswavi** [comment]
Hi @lishiyu, thank you for alerting this to this error. I'm sorry for the slow response - I was traveling this weekend and was not able to promptly look into this. We will be better about prompt support in the future.

Our PR above provides a stopgap solution, but the real problem seems to be an issue with OpenAI's tiktoken library (which I've created an issue for [here](https://github.com/openai/tiktoken/issues/196)).
