### ISSUE TITLE
 Evaluation metrics

### ISSUE THREAD

**Issue by chensimian** [neulab/prompt2model#367]
How can I modify the evaluation metrics mentioned below to evaluate locally instead of connecting to Hugging Face?
        metrics = [
            evaluate.load("chrf"),
            evaluate.load("exact_match"),
            evaluate.load("bertscore"),
        ]

**Comment by zhaochenyang20** [comment]
Sorry. What do you mean by connecting to HuggingFace? We are utilizing a toolkit called `evaluate` open-sourced by HuggingFace. I think there is no privacy concerns.

**Comment by viswavi** [comment]
I agree with @zhaochenyang20 - since Hugging Face is just a library here (and not an API), I'm curious what the issue with using this library is?

I'll also cross-post the reply I left for @chensimian when he emailed me this week for the same issue:
```
Unfortunately, our code directly uses the Hugging Face Evaluate library for our evaluation. You will have to change the code to support a change if you'd like to make one.

Fortunately, this should be pretty straightforward. Just use the "ground_truths" and "predicted_strings" to compute the metric of your choice (you can add this code here: https://github.com/neulab/prompt2model/blob/main/prompt2model/model_evaluator/seq2seq.py#L68-L70).
```
