### ISSUE TITLE
Missing openai.error module

### ISSUE THREAD

**Issue by MarkJYC001** [neulab/prompt2model#377]
When I try to run the `python prompt2model_demo.py`, there is a `ModuleNotFoundError: No module named 'openai.error'`.

I think this may have something to do with the openai library renew recently.

**Comment by viswavi** [comment]
Thank you for surfacing this issue, @MarkJYC001. #378 will address this (by simply specifying the exact litellm and openai verisons to use). We will merge this PR in a few minutes, then the demo will be operational again.

**Comment by saum7800** [comment]
For the future, we might consider looking at this discussion to update our scripts that use OpenAI https://github.com/openai/openai-python/discussions/742. `openai.error` is indeed one of the many things they have changed with the new release
