### ISSUE TITLE
gpt tokens?

### ISSUE THREAD

**Issue by AntDX316** [neulab/prompt2model#389]
At least 1 resource is 310GB and I couldn't download it because I'm trying to run it on Ubuntu VM and it cannot recognize the storage size even though it is at 404GB.

What does the OpenAI tokens even do? If it trains then it must cost a lot?

I'm not even sure what prompt2model even is. Are you creating another LLM with it?

**Comment by zhaochenyang20** [comment]
Sorry. I don't quite understand your problem.

> At least 1 resource is 310GB and I couldn't download it because I'm trying to run it on Ubuntu VM and it cannot recognize the storage size even though it is at 404GB.

What do you mean by this?

We use OpenAI API to generate/distill datasets for training. And we create/finetune another language model.

**Comment by AntDX316** [comment]
> Sorry. I don't quite understand your problem.
> 
> > At least 1 resource is 310GB and I couldn't download it because I'm trying to run it on Ubuntu VM and it cannot recognize the storage size even though it is at 404GB.
> 
> What do you mean by this?
> 
> We use OpenAI API to generate/distill datasets for training. And we create/finetune another language model.

yea, how much does that usually cost?
