### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by AntDX316** [neulab/prompt2model#390]
Is it like creating your own LLM?

**Comment by saum7800** [comment]
It's like creating your own small language model, for a task you can specify through a prompt and some examples. Feel free to play with it by running `prompt2model_demo.py` to see how it works

**Comment by 7flash** [comment]
And how much does it cost let's say to evaluate one of examples?

> It's like creating your own small language model, for a task you can specify through a prompt and some examples. Feel free to play with it by running `prompt2model_demo.py` to see how it works

**Comment by AntDX316** [comment]
> And how much does it cost let's say to evaluate one of examples?
> 
> > It's like creating your own small language model, for a task you can specify through a prompt and some examples. Feel free to play with it by running `prompt2model_demo.py` to see how it works

exactly

**Comment by zhaochenyang20** [comment]
> And how much does it cost let's say to evaluate one of examples?

For the example we used in our paper, generating 3000 examples for SQuAD costs 5$. Training cost depends on your device.
