### ISSUE TITLE
is there any generated training dataset?

### ISSUE THREAD

**Issue by XuanRen4470** [neulab/prompt2model#402]
I can only find the testing and validation dataset. is there a way to find any generated training dataset?

**Comment by vijay-cohere** [comment]
Hi! If you are using our python CLI, you can find the generated training dataset [here](https://github.com/neulab/prompt2model/blob/main/prompt2model_demo.py#L333C9-L333C26). If you are using the IPython notebook, you can find the generated dataset in the cell under "Generate Dataset".

It will be saved to disk if you've already run the pipeline, so you shouldn't need to re-run anything to obtain your dataset.

**Comment by viswavi** [comment]
Hi! If you are using our python CLI, you can find the generated training dataset [here](https://github.com/neulab/prompt2model/blob/main/prompt2model_demo.py#L333C9-L333C26). If you are using the IPython notebook, you can find the generated dataset in the cell under "Generate Dataset".

It will be saved to disk if you've already run the pipeline, so you shouldn't need to re-run anything to obtain your dataset.
